---
name: Question | 提问
description: Ask a question about this app | 向其他人询问关于这个app的问题
title: "[Question]"
labels:
  - "question"

body:
  - type: markdown
    attributes:
      value: |
        Please use [discusstion](https://github.com/GUETCourseTable/CourseTableAllPlatform/discussions/new?category=q-a-%E6%8F%90%E9%97%AE%E5%8C%BA) instead.
        请前往[讨论区](https://github.com/GUETCourseTable/CourseTableAllPlatform/discussions/new?category=q-a-%E6%8F%90%E9%97%AE%E5%8C%BA)提问

